_target_: model.ddpm.GaussianDDPM
denoiser_module:
  _target_: model.unet.UNetTimeStep
  channels: [3, 128, 256, 256, 384]
  kernel_sizes: [3, 3, 3, 3]
  strides: [1, 1, 1, 1]
  paddings: [1, 1, 1, 1]
  p_dropouts: [0.1, 0.1, 0.1, 0.1]
  time_embed_size: 100  #did not found this hp on the paper
  downsample: true
T: ${noise_steps}
lambda_variational: 0.0001
width: ${dataset.width}
height: ${dataset.height}
logging_freq: 1_000
input_channels: ${dataset.channels}
vlb: true
init_step_vlb: 1_000